
ALTER TABLE users 
    ADD COLUMN bio VARCHAR;
ALTER TABLE users 
    ADD COLUMN address1 VARCHAR;
ALTER TABLE users 
    ADD COLUMN address2 VARCHAR;
ALTER TABLE users 
    ADD COLUMN city VARCHAR;
ALTER TABLE users 
    ADD COLUMN state VARCHAR;
ALTER TABLE users 
    ADD COLUMN zip VARCHAR;
ALTER TABLE users 
    ADD COLUMN weight SMALLINT;
