
ALTER TABLE users 
    ADD COLUMN bio VARCHAR;
    ADD COLUMN address1 VARCHAR;
    ADD COLUMN address2 VARCHAR;
    ADD COLUMN city VARCHAR;
    ADD COLUMN state VARCHAR;
    ADD COLUMN zip VARCHAR;
    ADD COLUMN weight SMALLINT;

